### ISSUE TITLE
conference 肉哦，

### ISSUE THREAD

**Issue by mhz-0916** [Zyfgoup/conferenceroomfront#2]

**Comment by mhz-0916** [comment]
大佬，可以给我sql建表文么，谢谢！

**Comment by Zyfgoup** [comment]
> 大佬，可以给我sql建表文么，谢谢！

我上传到后端的仓库去了 你去下载就好了

**Comment by mhz-0916** [comment]
谢谢大佬





------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 11:04
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)

**Comment by mhz-0916** [comment]
数据库中已经添加了为啥还是密码错误，我试过部门的也是一样密码错误，是什么问题啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zyfgoup/conferenceroomfront"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 中午11:04
收件人:&nbsp;"Zyfgoup/conferenceroomfront"<conferenceroomfront@noreply.github.com&gt;;
抄送:&nbsp;"1287113424"<1287113424@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





  
大佬，可以给我sql建表文么，谢谢！
  
我上传到后端的仓库去了 你去下载就好了

**Comment by Zyfgoup** [comment]
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012

**Comment by mhz-0916** [comment]
老哥，我想在你的这个基础上再添加一个员工登陆模块，就是个人也能申请会议室的模块应该怎么搞，需要改哪些东西呢？





------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 14:23
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





 
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012

**Comment by mhz-0916** [comment]
兄弟看下qq，出现了点问题







------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 14:23
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





 
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012

**Comment by mhz-0916** [comment]
兄弟，最后还有个小问题，你看一下qq别的应该没问题了





------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 14:23
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





 
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012

**Comment by mhz-0916** [comment]
兄弟，今天有空么？





------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 14:23
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





 
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012

**Comment by mhz-0916** [comment]
兄弟，有两个问题咨询下！！！





------------------ 原始邮件 ------------------
发件人: Zyfgoup <notifications@github.com&gt;
发送时间: 2020年7月24日 14:23
收件人: Zyfgoup/conferenceroomfront <conferenceroomfront@noreply.github.com&gt;
抄送: mhz-0916 <1287113424@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[Zyfgoup/conferenceroomfront] conference 肉哦， (#2)





 
就这样看我也不知道什么原因 你看看浏览器控制台报错是什么  再后端中登录的的那个方法打印一下看下进没进到方法，还有我的Shiro是集成了Redis的  你得启动Redis先 我的Redis是设置了密码的 配置文件里有配置  解决不了的话 你加我QQ我看一下吧 619122012
